POST http://localhost:5000/api/users
Content-Type: application/json

{
    "name": "Mark",
    "email": "mark@mail.com",
    "password": "12345678"
}
###
GET http://localhost:5000/api/users

### sign in
POST http://localhost:5000/api/signin
Content-Type: application/json

{
    "email": "golden@mail.com",
    "password": "password"
}

###
GET http://localhost:5000/api/users/5fa7923a09b8e73d940ced5c

###
PUT http://localhost:5000/api/users/5fdb0d92de035e3cb883c38b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmRiMGQ5MmRlMDM1ZTNjYjg4M2MzOGIiLCJpYXQiOjE2MDgxOTczOTN9.zikyGAZOg6tgFPckOsJlDLGU2Z1r6397iyyMMhmx15o
Content-Type: application/json

{
    "lastName": "Chidzambwa"
}

###
DELETE http://localhost:5000/api/users/5fa7923a09b8e73d940ced5c

### create a category
POST http://localhost:5000/api/categories
Content-Type: application/json

{
    "categoryName": "Wearable Technology"
}

### retrieve categories
GET http://localhost:5000/api/categories

### retrieve auctions in a given category
GET http://localhost:5000/api/auctions/category/5fc33baa8f4b033f000edc59

### retrieve latest auctions added
GET http://localhost:5000/api/auctions/added/latest

### search auctions
GET http://localhost:5000/api/auctions?search=xbox&category=All

### retrieve auctions by bidder (all)
GET http://localhost:5000/api/auctions/bid/5fc1f0330c400d4094ad3fce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmMxZjAzMzBjNDAwZDQwOTRhZDNmY2UiLCJpYXQiOjE2MDc0OTU3NTB9.u8qMt-6gwaJ5wBOSJl2KAwwTYmNPXDZguLdcCDg5Nwc

### retrieve auctions by bidder (live)
GET http://localhost:5000/api/auctions/bid/live/5fc1f0330c400d4094ad3fce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmMxZjAzMzBjNDAwZDQwOTRhZDNmY2UiLCJpYXQiOjE2MDc0OTU3NTB9.u8qMt-6gwaJ5wBOSJl2KAwwTYmNPXDZguLdcCDg5Nwc

### retrieve auctions by bidder (won)
GET http://localhost:5000/api/auctions/bid/won/5fc1f0330c400d4094ad3fce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmMxZjAzMzBjNDAwZDQwOTRhZDNmY2UiLCJpYXQiOjE2MDc0OTU3NTB9.u8qMt-6gwaJ5wBOSJl2KAwwTYmNPXDZguLdcCDg5Nwc

### Retrieve orders by seller
GET http://localhost:5000/api/orders/seller/5fc1f0330c400d4094ad3fce
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmMxZjAzMzBjNDAwZDQwOTRhZDNmY2UiLCJpYXQiOjE2MDgzNTQ4MjJ9.-xPA83TTCiDlFDPT7E0Zbdp4yRPpPPR5zFEElNJFVm8

### Retrieve orders by buyer
GET http://localhost:5000/api/orders/buyer/5fc0d0588f7e4e3f7cb94342
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmMwZDA1ODhmN2U0ZTNmN2NiOTQzNDIiLCJpYXQiOjE2MDgzNTUyMDN9.aXd-FdKjKPDvOfQEHQee276Ptuogq91vs3XRMRBNYc4

###
GET http://localhost:5000/api/orders/status_values

###
GET http://localhost:5000/api/order/5fde93d2971a0910608e2077
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI1ZmMxZjAzMzBjNDAwZDQwOTRhZDNmY2UiLCJpYXQiOjE2MDgzNTQ4MjJ9.-xPA83TTCiDlFDPT7E0Zbdp4yRPpPPR5zFEElNJFVm8

### create admin
POST http://localhost:5000/api/admin 
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

### list all admins
GET http://localhost:5000/api/admin 

### admin login
POST http://localhost:5000/api/admin/signin
Content-Type: application/json

{
    "name": "admin",
    "password": "admin"
}

### list all users
GET http://localhost:5000/api/admin/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

### list all auctions
GET http://localhost:5000/api/admin/auctions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

### list all orders
GET http://localhost:5000/api/admin/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

### list all categories
GET http://localhost:5000/api/admin/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

### delete user
DELETE http://localhost:5000/api/admin/users/5fc1efd30c400d4094ad3fcc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

### delete auction
DELETE http://localhost:5000/api/admin/auctions/5fc466ef5c6f911990867e70
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

### add a category
POST http://localhost:5000/api/admin/categories
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U
Content-Type: application/json

{
    "categoryName": "Some Bullshit"
}

### delete a category
DELETE http://localhost:5000/api/admin/categories/60064e33cabf40382413ac07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MDAyNjNhOTc0MTU1YjIwN2M5NmMzM2UiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2MTA3NzI0NDd9.pYjBLnvw2WsvXXPOSZl4FXlAVu2oY7Qn-dn66mB509U

